### your site title here

title: 'Munindra Nath'
url: https://sideprojectme.github.io
baseurl: /projects
permalink: /:title
### exclude the instructions / write-up in the README.md

exclude:
- README.md
